# v2 syntax
version: '2'

# Named volumes
volumes:
  test-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    volumes:
      - test-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  # PHP (with Caddy)
  api:
    image: ambientum/php:7.2-nginx
    container_name: test-api
    volumes:
      - ./api:/var/www/app
    ports:
      - "3000:8080"
    links:
      - mysql

  web:
    container_name: teste-web
    build:
      context: ./web
    volumes:
      - ./web/src:/node-app/src
      - ./web/public:/node-app/public
    depends_on:
      - api
      - mysql
    links:
      - api
    ports:
      - "8080:8080"
      - "8788:8788"
